### ISSUE TITLE
 time latency 

### ISSUE THREAD

**Issue by bbrui** [LMAX-Exchange/disruptor#106]
I use one producer and one consumer ,one  handler event. 
When send big number event happen,i found event handle is low.
For example,I publish 10000 event.At sequence 800 ,event is A, the event A publish time is t1,and onEvent method  get event A ,the time is  t2. t2-t1 more than 10 seconds.because befere 800,the event handler is a liiter slow.it seems as single thread handler event.
I analyse the code fragment of  run() mehod in  BatchEventProcessor.java .i found  event is handle by sequence,if business handler is cost more time ,next sequence event need  last event handle firstly . 
 while (nextSequence <= availableSequence)
 {
                        event = dataProvider.get(nextSequence);
                        eventHandler.onEvent(event, nextSequence, nextSequence == availableSequence);
                        nextSequence++;
}

is it have a  good solution for this?thank you .

**Comment by mikeb01** [comment]
The disruptor is designed that each EventHandler is run in a single thread and that events are processed sequentially by that EventHandler.  This does mean that the slow processing of a single event can mean the slow processing of subsequent events.

In some cases you can make use of smart batching to improve the performance of the EventHandler, especially if the slowness is caused by I/O operations.

However if the behaviour that you want is to allow for another thread to pick up the event then you should consider a different concurrency construct, e.g. an PooledExecutor.
