### ISSUE TITLE
tryPublishEvent efficiency

### ISSUE THREAD

**Issue by wanglingsong** [LMAX-Exchange/disruptor#127]
I have an application which uses RingBuffer's tryPublishEvent api to pass data and discard them if the buffer is full.

I look at the source
```
    public boolean tryPublishEvent(EventTranslator<E> translator)
    {
        try
        {
            final long sequence = sequencer.tryNext();
            translateAndPublish(translator, sequence);
            return true;
        }
        catch (InsufficientCapacityException e)
        {
            return false;
        }
    }
```

The sequencer will throw an InsufficientCapacityException when the ring is full. The exception is caught and then return false.

It seems not so efficient to me when tryPublishEvent is triggered frequently in my application even though InsufficientCapacityException is already optimized by disabling stacktrace.

Is it possible to return a special sequence number for sequencer.tryNext() e.g. -1 for indicating a full status of the ring buffer instead of throwing exception?

**Comment by mikeb01** [comment]
I have thought about that optimisation and I may do it for the next big revision of the Disruptor.  When JDK 9 comes out I'm going to rewrite it using VarHandles and see if there are any other efficiency changes that I can bring in.  One of the drawbacks of return a negative value is often callers forget to check the value causing issues downstream.  So I would need to add additional checks on the publish path to make sure that it didn't receive bad values.  It would also require measuring as we may find that the additional branching caused by the check for negative values may hurt too.

**Comment by wanglingsong** [comment]
How about introducing an additional method sequencer.tryNextQuite() to return the negative value so that you can keep the current behavior for users and optimize tryPublishEvent by calling it internally.

**Comment by mikeb01** [comment]
It would mean changing the internals of the Sequencer class also and would require adding duplicate methods to handle both cases there too.  I don't think the win is sufficient enough to clutter up the API.

**Comment by wanglingsong** [comment]
That's reasonable. Btw, have you considered introducing some benchmark tools like [jmh](http://openjdk.java.net/projects/code-tools/jmh/) for measuring performance which I believe is more accurate.

**Comment by mikeb01** [comment]
I have, but multithreaded tests like the ones we have in the Disruptor are not straightforward.  JMH also doesn't do latency test particularly well.

**Comment by wanglingsong** [comment]
Thanks so much for the explanation!
