### ISSUE TITLE
Knowing when all event processors are running and ready

### ISSUE THREAD

**Issue by yrashk** [LMAX-Exchange/disruptor#142]
I have found no reasonable way to learn from Disruptor whether all event processors have effectively started. I ran into a situation when I am trying to publish an event right after disruptor's start and they are not being processed.

When I tried to insert a delay (and also check if ThreadPoolExecutor has a matching number of active threads), I am having a lot less missing event processing situations.

Perhaps exposing `consumerRepository` and `ConsumerInfo` will help as I can rely on `ConsumerInfo#isRunning`? 

Any thoughts whether it can be fixed this or another way, or how can the problem be avoided altogether?

**Comment by ajsutton** [comment]
I’m a little unclear on why you need to know this. You should setup the disruptor on one thread, call start() and then begin publishing events (from any thread).  Whether or not the consumer threads have actually been scheduled on a CPU and started shouldn’t matter because the consumers will start processing from sequence 0 when they do start.

Do you have some example code that shows the problem with events getting lost?

**Comment by mikeb01** [comment]
Implement the LifeCycleAware interface on your EventHandler.  You will get a callback when the processor is started.

**Comment by mikeb01** [comment]
Also how are you setting up the Disruptor?  You shouldn't be losing events if the EventHandlers are added correctly, before publishing begins.

**Comment by mikeb01** [comment]
Haven't heard feedback on this for sometime, so I'm closing.
