### ISSUE TITLE
CPU exhaustion in MultiProducerSequencer

### ISSUE THREAD

**Issue by simon-greatrix** [LMAX-Exchange/disruptor#157]
Incorrect use of LockSupport is causing CPU exhaustion in MultiProducerSequencer. This causes extreme performance degradation.

My JVM gets stuck in the `next(int)` method. This method parks the thread for a single nanosecond and then retests the condition. This is so fast that my CPU could only execute 3 instructions (it being a 3GHz CPU) before restarting which is probably less than a single JVM byte code instruction. My guess is that the JVM is actually repeatedly re-executing this block of code causing all other threads to be starved of CPU.

The use of the Java “LockSupport.parkNanos” method which is what LMAX disruptor is doing is exactly what the documentation (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/LockSupport.html ) says NOT to do, which says: “park serves as an optimization of a "busy wait" that does not waste as much time spinning, but must be paired with an unpark to be effective”, but LMAX does not pair it with an unpark, which is why it is not effective.

I encountered this issue whilst logging with Log4J on Windows with Java 8. Many threads are writing into the sequencer, but only one thread is reading from it to write the log file. The reading thread is starved of CPU whilst the writing threads spin madly waiting for space in the buffer.

**Comment by mikeb01** [comment]
This is a place where we have had to make an awkward trade off.  One features of the Disruptor is that is can work in a manner that avoids Lock.{park,unpark}, but to do so it has to fall back to some sort of busy-wait operation.  For some of the simple cases it would be possible to add a optional support for having the consumer unpack a waiting publisher thread, but for some of the more complex cases, this is not so easy (if even possible without destroying performance for the cases we really care about).  I'll look at an enhancement where the user can do optionally include support for this.

However, the Disruptor was designed to work in low-latency systems, where the number busy threads tends to be smaller than the number of available cores.  In these system using LockSupport.parkNanos() tends to be quite effective.  If your system does not fall into that category you may want to consider a different appender in your Log4j configuration.

For the specific case of log4j.  We have our own Disruptor based appender, in which we use tryNext() rather than next() and drop events (with some additional controlled logging to stderr and MBean monitoring) as we believe that stalling application flow for the sake of logging is wrong option to take.  I did bring up this option with them, but they rejected our approach.

Just a couple of corrections around LockSupport.parkNanos(1).  While the code suggests that it would park for a nanosecond, the reality on most operating system is that the pause is much longer than that.  On Linux it tends to be around 60µs on Windows more like 200µs (depending on version).

As to the "LMAX disruptor is doing is exactly what the documentation (...) says NOT to do".  Strong recommendations from SUN/Oracle is not always a reason not to do something, we use the Unsafe after all.

**Comment by simon-greatrix** [comment]
Thanks for the clarification Mike,

It sounds to me like the problem is actually that Log4J uses Disruptor at all, and not a problem with Disruptor. Log4J claims to be a general purpose logging framework but by using Disruptor they are limiting themselves to only Sun JVMs (where Unsafe is available) and only software that has less threads than cores where behaviour similar to a busy spin is acceptable.

I will pursue this from the Log4J end now I know that Log4J is using your library in a manner that it simply was not designed for.

**Comment by epickrram** [comment]
Perhaps a configurable back-off strategy in the producer would be
worthwhile. Though we'd still need to ask library maintainers to use it, it
would allow users to trade blocking for cpu time.

**Comment by mikeb01** [comment]
I don't think that there is anything wrong with using the Disruptor in Log4j (although I may criticise some specifics of their implementation).  They've done some interesting work of late on garbage free logging and improving performance.  The important point is that there is no 1 size fits all solution.  There are a number of applications that for which the async appender configuration that uses the Disruptor is the most suitable.  However, there are some applications which it isn't, but you aren't forced to use the Disruptor for those (it's only enabled with the Async appender).  And you can always write your own appender.

BTW, the Unsafe, while not part of the spec or standard, but it tends to a de-facto standard an is supported on most production JVMs (IBM, Oracle, OpenJDK derivatives, Azul,...).

**Comment by mikeb01** [comment]
A configurable backoff would work well.  It is also pretty easy for users to build their own on top of RingBuffer.tryNext().
