### ISSUE TITLE
EventReleaser.release()

### ISSUE THREAD

**Issue by ulfsar** [LMAX-Exchange/disruptor#181]
hi all,
        in com.lmax.disruptor.WorkProcessor
        I can't understand the method sequence.set(Long.MAX_VALUE);
        Can you explain in detail?

**Comment by mikeb01** [comment]
This is a mechanism to signal to the Disruptor that the work handler has taken a copy of the in data in the event and that the event passed into the WorkHandler is no longer needed and can be overwritten by a publisher.  This is useful if some of the WorkHandlers are potentially quite slow, so that they don't hold up the rest of the system.
