### ISSUE TITLE
Question about the RingBuffer

### ISSUE THREAD

**Issue by brianhks** [LMAX-Exchange/disruptor#189]
From my understanding you are trying get all the values in the ring buffer to be in a cache line to make reading them fast.  This code however:
`private final Object[] entries;`
is just an array of pointers and the objects are off somewhere else in memory.  

Admittedly I'm at the edge of my understanding on this are you doing some other magic that I'm not seeing?

**Comment by mikeb01** [comment]
I assume you are asking how we work nicely with the cache rather than actually fit all the data into a cache line (a cache line is only 64 bytes).

We are limited by the Java's layout constraints, so with the default implementation of the RingBuffer we rely on temporal locality rather than spacial locality to gain cache-friendly benefits.  The main way this is achieved is by using the event factory to pre-create events at the same time during start up and reuse the objects.

However, this may not be sufficient in some cases, so it is possible to disconnect the sequencer from the ring buffer and provide your own ring buffer implementation.  You can see an example of putting the data off heap in flat layout the [offheap benchmark](https://github.com/LMAX-Exchange/disruptor/blob/master/src/perftest/java/com/lmax/disruptor/offheap/OneToOneOffHeapThroughputTest.java).
