### ISSUE TITLE
Disruptor allocates many AbstractQueuedSynchronizer$Node objects in idle mode

### ISSUE THREAD

**Issue by doom369** [LMAX-Exchange/disruptor#227]
Hello. I'm using lmax disruptor (version 3.4.2) with log4j2 (2.11.0) logger in my project. Recently, during profiling, I found the abnormal number of `AbstractQueuedSynchronizer$Node` objects in my heap.

I did simple test and found that disruptor spams ~5kb of such objects per seconds in idle mode when server does nothing.

![screenshot from 2018-04-22 01-14-12](https://user-images.githubusercontent.com/1536494/39089225-7d626778-45ca-11e8-96c5-7c4ebf89a50d.png)

Allocation tree:

![screenshot from 2018-04-22 01-07-29](https://user-images.githubusercontent.com/1536494/39089215-384b0528-45ca-11e8-84dc-b85266acfff9.png)

Is that expected allocations? Or bug?

```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by mikeb01** [comment]
Not really surprised as this is internal to the JDK implementation of the Condition variable.  We generally haven't worried about profiling the blocking wait strategies.  However, I can re-write the strategy to use synchronized blocks instead of juc.Lock, which appears to not require the allocation.

**Comment by doom369** [comment]
Hm. Interesting. Thanks.

**Comment by JakubWagner1019** [comment]
Any idea why this change didn't end in any of the official library releases?

**Comment by doom369** [comment]
@JakubWagner1019 there were no new disruptor releases as far as I know. But yeah, would be nice to see one after 2 years :).

**Comment by Palmr** [comment]
> Hello. Any idea why this change didn't end up in any of the official library releases?

I would wager it was because this change wasn't worth doing a release for. As Mike mentioned "We generally haven't worried about profiling the blocking wait strategies".

Generally, if you're using the disruptor it's because you want low latency and high throughput. If you use something like the `BlockingWaitStrategy`, you're not going to get that so there's not much focus there.

The change Mike made is still in the code and will be in the v4 release, hopefully before the end of the year :crossed_fingers: 

> @JakubWagner1019 there were no new disruptor releases as far as I know. But yeah, would be nice to see one after 2 years :).

Not exactly true, see v3.4.4 though not exactly wrong either :)
