### ISSUE TITLE
Can parallelly process different eventHandler type when using workerPool 

### ISSUE THREAD

**Issue by dukeduke2002** [LMAX-Exchange/disruptor#294]
The following code can process Handler1, Handler2 parallelly, both of them finished, then process Handler3.
```java
disruptor.handleEventsWith(new Handler1(), new Handler2()).handleEventsWith(new Handler3());
```

Here is my question. Can we use handleEventsWithWorkerPool method to realize the same function? the following code can not make out. We want to parallelly process handler1 and handler2.

```java
disruptor.handleEventsWithWorkerPool(new Handler1(), new Handler1(),new Handler2(),new Handler2()).thenHandleEventsWithWorkerPool(new Handler3(),new Handler3());
```

**Comment by a807966224** [comment]
麻烦问下，消费者处理是同步事件，怎么做到一个线程能并发处理几百万的业务？

**Comment by andyphillips** [comment]
Well, 


  At the most basic level, a 3Ghz processor can handle several hundred to maybe a thousand rops/microsecond. If you get out of its way, have a lock free architecture and lay out your memory so you take advantage of cache rather than working against it, then several million transactions per second is the natural result. 


  A network card processes several million packets per second using the same concepts as disruptor. That's not surprising. Equally unsurprising that the disruptor can do the same rates. 


I'm not saying it's easy, just not impossible. 


Andy 

-- 

Dr Andy Phillips 



On 9 Jan 2022 03:56, "Scott.WDR" ***@***.***> wrote: 

麻烦问下，消费者处理是同步事件，怎么做到一个线程能并发处理几百万的业务？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
