### ISSUE TITLE
disruptor upgrade to jdk11

### ISSUE THREAD

**Issue by violetgo** [LMAX-Exchange/disruptor#298]
Hello, I found that in the disruptor framework, some code uses `sun.misc.Unsafe`

![image](https://user-images.githubusercontent.com/5086059/87389963-679b6100-c5da-11ea-981a-419ace422a4b.png)

but after jdk9, sun.misc.Unsafe is not recommended, and it is recommended to replace it with `Variable Handles`, (http ://openjdk.java.net/jeps/193).
And in jdk11, `sun.misc.Unsafe` has been removed.

So, can disruptor run well in jdk11? If not, is there any plan to support jdk11?

**Comment by Palmr** [comment]
As far as I can tell `sun.misc.Unsafe` was not removed in JDK11, it's still there in OpenJDK and the Disruptor compiles and runs fine on OpenJDK 11.
Some functions were moved but the Disruptor was not using these ( see https://blogs.oracle.com/javamagazine/the-unsafe-class-unsafe-at-any-speed#anchor_4 )

You are right that using Unsafe is not recommended and using VarHandles is the way forward.
This is something we are currently working towards, so that the Disruptor will continue to work in future versions of Java where Unsafe might be fully unsupported.

**Comment by violetgo** [comment]
yeh, i have test sun.misc.Unsafe in jdk11. it still work,  thanks for your replay~
