### ISSUE TITLE
There may be some problems in disruptor shutdown(final long timeout, final TimeUnit timeUnit) method

### ISSUE THREAD

**Issue by adol001** [LMAX-Exchange/disruptor#381]
current code
```java  
    public void shutdown(final long timeout, final TimeUnit timeUnit) throws TimeoutException
    {
        final long timeOutAt = System.currentTimeMillis() + timeUnit.toMillis(timeout);
        while (hasBacklog())
        {
            if (timeout >= 0 && System.currentTimeMillis() > timeOutAt)
            {
                throw TimeoutException.INSTANCE;
            }
            // Busy spin
        }
        halt();
    }
```

1 if timeout, halt method isn't called, resource leak and worker thread still works
2
```java
        while (hasBacklog())
        {
            if (timeout >= 0 && System.currentTimeMillis() > timeOutAt)
            {
                throw TimeoutException.INSTANCE;
            }
            // Busy spin
        }
```
cost too much cpu resource, hope to provide another shutdown way, for example
```java
        while (hasBacklog())
        {
            Thread.sleep(1) // 100%cpu => 3%cpu
            if (timeout >= 0 && System.currentTimeMillis() > timeOutAt)
            {
                throw TimeoutException.INSTANCE;
            }
        }
```

**Comment by Palmr** [comment]
For point 1, if a timeout happens the method throws `TimeoutException`, and this is telling your code the shutdown was not successful.

If we called `halt()` despite the timeout then yes, the event processor thread would be stopped and resources freed. But the events it had left in the backlog would not be processed and you would have no way of knowing which events had, or had not been processed. Therefore I do not think we should call halt on timeout as part of the code.

If in your application you do want to call `halt()` regardless of a `TimeoutException` then you can catch the `TimeoutException` and call `Disruptor::halt` from your application.


For point 2, this library is designed for low latency. To get low latencies we typically make full use of the CPU, so seeing high CPU use is not a concern.
Our typical use cases for this library involve having the Disruptor start when the application starts and shutdown only when the entire application is exiting. So any CPU use during shutdown from busy spinning is very much inconsequential.
What use case do you have where when you shut down the Disruptor you are concerned about CPU usage?

The suggested change with a `Thread.sleep(1)` will indeed reduce CPU usage, but does not work well with the timeout logic for the shutdown. For example if you had a 1 second timeout, and the backlog of events cleared in 500ms, the thread sleep would block while clearing, then enter the timeout check and throw a `TimeoutException`, which would be incorrect.
If making a change to sleep/yield/use a WaitStrategy, it would be better placed where the comment is right now saying `// Busy spin`.

**Comment by adol001** [comment]
@Palmr 
Point1: I think shutdown without side effects is more important than knowing which events had, or had not been processed. 
At least there should be documentation describing this behavior.

Point2: If the CPU resource consumption you need for your work is less than busy spin need, and you are not sensitive to strict timeout, you will feel particularly painful for busy spin.
So I hope to provide another shutdown method in addition to the current method for users to choose

**Comment by Palmr** [comment]
> Point1: I think shutdown without side effects is more important

If that's your use case, wrap the code with a try/catch (which you must do anyway as it's a checked exception) and call `halt`.

> At least there should be documentation describing this behavior.

The javadoc already says:

```java
/**
 * ...
 * @throws TimeoutException if a timeout occurs before shutdown completes.
 */
```

Which should be clear enough that this exception is thrown if a timeout occurs before shutdown completes. If you wish to force the shutdown to complete, that's not what this method will do, or is documented to do.

> Point2: If the CPU resource consumption you need for your work is less than busy spin need, and you are not sensitive to strict timeout, you will feel particularly painful for busy spin.
So I hope to provide another shutdown method in addition to the current method for users to choose

I think we still need some details on your use case here and why having CPU use is "painful".

**Comment by adol001** [comment]
@Palmr 
Point1:
Sorry for the misleading description.

/**
 * ...
 * @throws TimeoutException if a timeout occurs before shutdown completes.
 * If an TimeoutException is thrown, worker threads are still working. If you want to force a stop, please catch TimeoutException and call halt
 */
I think it is a good idea to add similar comments.
By the way, I did not find Thread::interrupt to stop thread. Maybe it will be better for adding it to stop longtime io work.

Point2:
We are in big data environment such as yarn. The cpu resource consumption of each task is designed fixed. When shutdown, busy spin will take up additional cpu resources. it will interfere with other jobs running in yarn, Especially real-time jobs like flink or spark streaming.
So we hope to have another shutdown method that saves cpu resources

**Comment by Palmr** [comment]
It sounds like in your case you don't mind not handling remaining events in the backlog?
And it seems you want to always stop the event processor?

If so you probably should just be calling `Disruptor::halt` rather than `Disruptor::shutdown`.

`shutdown` tries to gracefully stop the processor, making sure all pending entries are processed. Then it calls `halt`.
Since you don't seem to mind not processing backlogged events, and you don't want the CPU overhead of waiting for them to process, perhaps calling `halt` is what you really want to do?

**Comment by adol001** [comment]
![2021-06-18 11-28-17 的屏幕截图](https://user-images.githubusercontent.com/15359410/122502059-767b6680-d028-11eb-8775-621d65241f3b.png)
As a developer, you should consider the general situation. 

In my case, multiple disruptors form a complex processing chain. For high performance, the buffer pools are large. Usually the entire chain will be completed in tens of seconds, but sometimes it can be over ten minutes. So calling halt directly does not meet our needs, we need to call the shutdown method with a timeout param.

If the user really cares about the unfinished event, it can record the input event in the producer, and record the event completion when the handler is completed. In this way, it can get unfinished events.

**Comment by Palmr** [comment]
Your use case is still not very clear to us.

Are you starting a Disruptor instance, begin publishing and then straight away calling shutdown, knowing that it will block until all events are processed? And because that processing is slow the shutdown is sat in a busy-spin for potentially tens of seconds to minutes?

Worth noting that you don't have to use the `Disruptor` class only. Your use case seems out of the ordinary for Disruptor use, you could use the `RingBuffer` and `ConsumerRepository` directly, writing any code you like in place of the shutdown method.

If you wish to make a change to the `Disruptor` class however, I would accept sending us a Pull Request with:

 - A new `Disruptor::shutdown` method which takes a `ShutdownWaitStrategy`
 - The existing `Disruptor::shutdown` method should call this new method with a `BusySpinShutdownWaitStrategy`
 - `ShutdownWaitStrategy` implementations for Busy Spin, Yielding, & Sleeping
 - Tests, verifying each strategy still allows draining the backlog, as well as testing the timeout still happens correctly

**Comment by adol001** [comment]
OK, I will try

**Comment by grumpyjames** [comment]
We hope success was had.
