### ISSUE TITLE
Question about com.lmax.disruptor.MultiProducerSequencer#initialiseAvailableBuffer

### ISSUE THREAD

**Issue by horizonzy** [LMAX-Exchange/disruptor#388]
https://github.com/LMAX-Exchange/disruptor/blob/db7a901bd25b87782b449d531b06395168becf63/src/main/java/com/lmax/disruptor/MultiProducerSequencer.java#L187-L195

Hi, I notice that code to initialise available buffer is from max to min, and set index `0` at end.

Why not use
```
    private void initialiseAvailableBuffer()
    {
        for (int i = 0; i < availableBuffer.length; i++)
        {
            setAvailableBufferValue(i, -1);
        }
    }
```
I want to know is there any special meaning?

**Comment by Palmr** [comment]
It seems it has been this way since that code was written with 4f41351 going from Disruptor 2 -> 3

The change introducing the `MultiProducerSequencer` is described in the changelog:

> - Remove claim strategies and replace with Publishers/Sequences, remove pluggability of claim strategies.
> - Introduce new multi-producer publisher algorithm (faster and more scalable).

---

Initialising them in a decrementing loop might be a good idea if another thread was pending on the first item changing, as you might want to make sure that was the last item to get changed. But this happens in the constructor so no other threads should have access to that until the entire method is complete.

I also remember something about decrement loops being faster as it's comparing to zero, which is faster than an arbitrary compare. I last used this knowledge in the mid 2000's using another language however and I'm not sure how true this holds with a modern CPU & JVM however. Plus, this code is only invoked in a constructor, micro-optimisations for speed would be an interesting choice to make.

Why it has a split to set specifically the last time, also no idea. I have asked a few of my colleagues and aside from wild speculation we don't have any facts for why it's like this.

---

Importantly the tests all still pass despite changing the code to the following example:

```java
private void initialiseAvailableBuffer()
{
    Arrays.fill(availableBuffer, -1);
}
```

These changes were put in around 2012, long before my time, so I am not aware of any historical reasons for it being this way.
I wonder if @mikeb01 is about and has any recollection, perhaps this was a common pattern to get around some issue?

**Comment by horizonzy** [comment]
Thanks for your detailed reply.

**Comment by mikeb01** [comment]
> Initialising them in a decrementing loop might be a good idea if another thread was pending on the first item changing, as you might want to make sure that was the last item to get changed. But this happens in the constructor so no other threads should have access to that until the entire method is complete.

This was essentially the reason that the code is the way it is.  While it only happens to be called from the constructor as this point, there's nothing about that method that enforces that - so there is a small element of future proofing in case it was decided that re-initialising and reusing a Disruptor would be a desired feature.  This code is shaped such that it requires the person changing it to consider the visibility and ordering of the values in this array (note that `setAvailableBufferValue` uses release semantics).  

The reverse order was part of the first implementation pass as it ensured that the last element to be initialised would be the 0-th one.  However I thought that making the 0-th element initialisation the last one should be explicit so I pulled it out of the loop.  The reverse order of the array is no longer really relevant, but I left it that way as it made sense (to me at the time) that if want the 0-th one done last then we may as well continue to do the whole loop in reverse.

If you wanted to rely on the release edge provided by the constructor to ensure visibility and use `Arrays.fill` to initialise the values in the buffer, then I would consider in-lining and removing the `initialiseAvailableBuffer` method.

**Comment by horizonzy** [comment]
Thanks, get it.
