### ISSUE TITLE
Why  RingBuffer:getBufferSize return int,   RingBuffer:remainingCapacity  return long ?

### ISSUE THREAD

**Issue by lich0079** [LMAX-Exchange/disruptor#401]
Why  RingBuffer:getBufferSize return int,   RingBuffer:remainingCapacity  return long ?

Just wondering in which case that   remainingCapacity  may exceed  bufferSize therefore need a long type ?

<img width="654" alt="截屏2021-11-05 15 34 59" src="https://user-images.githubusercontent.com/872418/140474683-88b665ab-bfc1-4e98-9d51-59e32977df1d.png">

**Comment by Palmr** [comment]
> Why RingBuffer:getBufferSize return int, RingBuffer:remainingCapacity return long ?

The only reason I can see that it is `long` is because the implementations of `Sequenced::remainingCapacity` use the sequence numbers in their calculations. The sequence numbers are `long`, so for that method to return an `int` we would need to cast the result of the calculation to `int`.

> Just wondering in which case that remainingCapacity may exceed bufferSize therefore need a long type ?

I do not think `Sequenced::remainingCapacity` would ever exceed `Sequenced::getBufferSize`.

---

Making it return `int` and changing the implementations to cast their result to an `int` should be safe to do. Implementations of `Sequenced::remainingCapacity` always return the ring buffer size minus the difference between produced and consumed sequences. Meaning the return value should be ring buffer size or lower.
However, changing this would have a knock-on effect for callers of `Sequenced::remainingCapacity`, which ends up public via `RingBuffer::remainingCapacity`.
I do not think changing this would be worth it.
