### ISSUE TITLE
会吃掉消息。

### ISSUE THREAD

**Issue by shakarelic** [LMAX-Exchange/disruptor#404]
新增：
![image](https://user-images.githubusercontent.com/8683348/145555443-410c3b82-5589-43e9-a239-2b1f379eba13.png)
![image](https://user-images.githubusercontent.com/8683348/145555422-d3b6def2-6ec0-47cc-90e4-6935ffc0fdc0.png)

消费:
![image](https://user-images.githubusercontent.com/8683348/145555528-8dc77c6e-a5e0-4b21-bcc8-b0d98d5df865.png)
![image](https://user-images.githubusercontent.com/8683348/145555562-68a0e46d-e4bc-447c-8d54-3ac69b0070c5.png)

数量
![image](https://user-images.githubusercontent.com/8683348/145555189-fd4c31a8-3802-4918-8929-0f6554c4b198.png)

**Comment by jptx1234** [comment]
在github中开源项目中提疑似bug类issue的正确方法：在本地新建项目，使用最少的代码复现出你遇到的问题，然后把此项目上传到github一个新的仓库中，把仓库链接贴在issue中。或者把此项目打包压缩成zip，拖拽到文本框中，上传附件。这样别人能够很容易复现问题，而不是靠这几张代码截图进行猜测。另外，在国际合作的项目中要使用英文提问，自己英语水平差也没关系，哪怕用谷歌翻译也行。目前 Disruptor 项目的维护团队几乎都不懂中文。

For people who can't read Chinese: The author is troubled by a problem that Disruptor may have 'eaten' the data. And he has posted screenshots of producers and consumers.

**Comment by MendelMonteiro** [comment]
Could we see the code for `incrementDisruptorQueueSize` and `decrementDisruptorQueueSize`?

**Comment by shakarelic** [comment]
> 在github中开源项目中提疑似bug类issue的正确方法：在本地新建项目，使用最少的代码复现出你遇到的问题，然后把此项目上传到github一个新的仓库中，把仓库链接贴在issue中。或者把此项目打包压缩成zip，拖拽到文本框中，上传附件。这样别人能够很容易复现问题，而不是靠这几张代码截图进行猜测。另外，在国际合作的项目中要使用英文提问，自己英语水平差也没关系，哪怕用谷歌翻译也行。目前 Disruptor 项目的维护团队几乎都不懂中文。
> 
> For people who can't read Chinese: The author is troubled by a problem that Disruptor may have 'eaten' the data. And he has posted screenshots of producers and consumers.

牛逼了，有些时候别人不是求你，是告知你这个问题，关键点都贴出来了，要看就看不看拉倒。看不懂你可以不看啊，气急败坏个什么。这么大的一个问题，有人指出不感激，还站在说话不腰疼。spring、netty这些项目有人提出疑问，都没有跪族跳的那么快，评一个美团代码的bug，居然还有跪族在这bb，完全不是一个合作态度。

**Comment by shakarelic** [comment]
> Could we see the code for `incrementDisruptorQueueSize` and `decrementDisruptorQueueSize`?

AtomicInteger：incrementAndGet And decrementAndGet
img mean：
push data 1100 times
wu test customer output log 2 type, and times equivalent:
1)onevent output times between 300 and 400
2)disruptorQueue  output times 1100-（surplus：726）

**Comment by MendelMonteiro** [comment]
Could we see the code ?

**Comment by MendelMonteiro** [comment]
@shakarelic, as @jptx1234 mentioned, would it possible to provide a project that reproduces the issue?

**Comment by jptx1234** [comment]
> 

@shakarelic 来来来小伙子，我上面哪句话显得气急败坏了，哪句话丢人现眼了，我的回复可没有经过任何编辑，你还编辑了下加了个丢人现眼四个字。另外，Disruptor不是美团做的，这是lmax交易所做的项目，根本不是中国人开发的。还“跪族”？遵守国际约定叫跪了？
话说回来，你还是贴个代码zip包吧，这样人家维护者可以快速复现问题。

**Comment by shakarelic** [comment]
> 

来来来老大爷，来一个国际约定贴出来。真的丢人现眼，真的跪族。
话说回来，使用到的核心代码都贴出来了，真正的维护者不会动不动要上传代码。你去大一点的社区看看，动不动让上传demo么？这是你的国际约定？

**Comment by shakarelic** [comment]
> > 
> 
> @shakarelic 来来来小伙子，我上面哪句话显得气急败坏了，哪句话丢人现眼了，我的回复可没有经过任何编辑，你还编辑了下加了个丢人现眼四个字。另外，Disruptor不是美团做的，这是lmax交易所做的项目，根本不是中国人开发的。还“跪族”？遵守国际约定叫跪了？ 话说回来，你还是贴个代码zip包吧，这样人家维护者可以快速复现问题。

sorry,i thought this is MeiTuan's project ,so i use chinaese.但是我不需要你来zhuangbishiguai的来指导。

**Comment by SteafanMrZhou** [comment]
你用官方例子去改造一下你的这个场景，看看还有没有你这个问题。

You use official examples to transform your scene and see if you still have this problem.

**Comment by Palmr** [comment]
Hi @shakarelic , as mentioned English is our main language here, but I have translated some of the posts here to try and figure out what's going on.

As others have mentioned, posting your sample code to reproduce the issue directly here in a code block (\`\`\` in markdown) or as a gist / commit somewhere will get the best response from us as we can then fully see the issue.

I find it difficult to see what the issue is?
In your screenshot with the log output, are you wondering why the `disruptorqueuecount` appears to stop changing? Showing there are 726 events published that never got consumed?

Your consuming code has a `Thread.sleep` in it which will pause each event on average 500ms, so the log not showing progress on the consumer side is not all that unexpected? You would have to wait longer, and depending how the code is set up, is something killing the consumer thread before it is finished?

If the gating has been misconfigured the ringbuffer could also be wrapping and then all bets are off.

To be able to help we will need to know how the ringbuffer is set up with the producer and consumer.

**Comment by kingsmao** [comment]
这瓜保熟吗？

**Comment by grumpyjames** [comment]
We don't seem to be making any progress here; it's not even particularly clear that this repository was the intended destination of the issue.
