### ISSUE TITLE
[Question] How to test batch behavior? 

### ISSUE THREAD

**Issue by tomerarazy** [LMAX-Exchange/disruptor#434]
Hi, I really love this project, switching to the Disruptor has improve our performance significantly and also cleaned up the code.

Now I'm adding some batch handling strategy in our code and I'm not quite sure how to test this.
The scenario is very simple - I want to publish to events that would processed as a single batch by the event handler but I don't know how I can "pause" the event handler so he won't process them as 2 batches of 1.

I saw the Disruptor class has a "halt" method which sounds like it will do something similar but I couldn't find how to resume it afterwards.

**Comment by tomerarazy** [comment]
Hi @ocoanet
I'm not worried about Disruptor batch implementation, I'm worried about my logic :-)
I'm writing integration tests so while calling the handler directly is possible it's not preferable due to which thread invokes the handler.
Same goes for publishing events before starting the disruptor - we're running multiple tests and they are all using the same disruptor instance.

**Comment by ocoanet** [comment]
Ok :)

You can try to publish events using the batch publication (`next(int)` and `publish(long, long)`). Given large publication batches, it would be quite unlikely that your handler would not process batches. But this approach would not be deterministic.

### Option A

You can also inject a "fake" message handler that would run as the first handler of the Disruptor, before your real handler. The fake handler would be configured to "block" in `onEvent` and you would "unblock" it manually to release the messages (using synchronization primitives).

Pseudo code:
```
disruptor.handleEventsWith(fakeHandler).then(myHandler);
disruptor.start();

ringBuffer.publishEvent(...);
ringBuffer.publishEvent(...);
ringBuffer.publishEvent(...);
ringBuffer.publishEvent(...);

fakeHandler.unblock();

// myHandler should process first event and then all remaining events as a single batch
```

### Option B

You can also inject a "synchronizer" in your real handler:
```
public void onEvent(...)
{
    synchronizer.wait();
    // impl
}
```
The synchronizer would be a "noop" implementation in the production code but would a useful to force batch generation in your tests. I do not really like this option because it impacts the real handler code.

**Comment by ocoanet** [comment]
> we're running multiple tests and they are all using the same disruptor instance.

It might be hard to get stable test results if you reuse the disruptor instances.

**Comment by tomerarazy** [comment]
Thanks @ocoanet , Option A was my idea as well, so I think I'll go in that route.

As for reusing the Disruptor instance - you're correct but we're being careful about it :)
