### ISSUE TITLE
Unable to set disruptor as singleton

### ISSUE THREAD

**Issue by lsl6666** [LMAX-Exchange/disruptor#454]
**Describe the bug**
disruptor version: 3.44

I want to use the disruptor as a singleton class to facilitate subsequent startup and shutdown. But when I get the object for the first time, it is correct. When I end the execution and shutdown for the first time, the second acquisition will report an error method throwing 'java.lang.NullPointerException' exception. Could not evaluate com.lmax.disruptor.dsl.BasicExecutor.toString()

![image](https://github.com/LMAX-Exchange/disruptor/assets/67491763/510184cd-6fb9-4d86-b068-c987560e4b4a)

**To Reproduce**
A test replicating the bug will be more helpful than just a description of your issue.
For example, this can be a JMH test showing a performance issue or a unit test showing a logic error.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. windows10]
 - Version [e.g. 3.4.4]
 - JVM Version [e.g. oracle jdk1.8]

**Additional context**

**Comment by SteafanMrZhou** [comment]
你这种直接返回 instance 的方式是错误的，instance 百分百为空，因为你的 instance 被定义为 static 的，且是 final 类型，所以无法动态获取 instance 实例，所以你应该使用访问静态类或静态资源的方式获取 instance 并返回，如下代码：

Your method of directly returning **instance** is wrong, **instance** is 100% empty, because your **instance** is defined as static and final type, so you cannot dynamically obtain **instance** instance, so you should use access to static class or static resource way to get **instance** and return, the following code:

`DisruptorFactory.instance`

**Comment by SteafanMrZhou** [comment]
@lsl6666 你好，这个问题还有吗，没有的话要关闭这个 issue 了。
