### ISSUE TITLE
FixedSequenceGroup What does this class do?

### ISSUE THREAD

**Issue by chenggwang** [LMAX-Exchange/disruptor#458]
`
dependentSequence = new FixedSequenceGroup(dependentSequences)

public FixedSequenceGroup(final Sequence[] sequences)
    {
        this.sequences = Arrays.copyOf(sequences, sequences.length);
    }`
Why not just use dependentSequence？

**Comment by Palmr** [comment]
Not entirely sure since the code dates back to 2012.

But I would suppose it's because the array of `Sequence` is passed in by users of the Disruptor and therefore could be mutated by code outside the Disruptor code. If this were to happen it would likely lead to undesirable results.

The name **Fixed**SequenceGroup also helps my supposition that this was done intentionally to ensure the array of sequence was not changed.
