### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by yuanChina** [LMAX-Exchange/disruptor#486]
![image](https://github.com/user-attachments/assets/09890e79-60fd-4f8d-87a2-1d8642f49d03)

According to the picture, the optimal performance is 1p1c. I would like to know if this means that putting all the logic into one handler is the best solution Which situation is recommended for us to use 1p2c or 1p3c? For example, I created two handlers, one for handling business logic and one for clearing events Is it best for me to merge these two handlers into one in this situation?

**Comment by yuanChina** [comment]
> It will depend on the application and workflow. One may for instance perform a sequence of independent tasks before processing an event. Think of things like logging or replication, these would result in three consumers like the example. It's not clear what you mean by clearing the event. If you mean clearing it out before reuse, in most cases it seems sufficient to overwrite it.

Does the above example mean higher performance if I put three processing logics into one handler.
And clear event is also an example, which can be understood as one of the logics.

**Comment by SamBarker** [comment]
>I would like to know if this means that putting all the logic into one handler is the best solution Which situation is recommended for us to use 1p2c or 1p3c? 

As @iziamos suggests if you have independent tasks its better to split them into multiple consumers. So that the observed latency of the event is that of the slowest task and not the sequential total. 

There is no generic advice to give about the number of consumers as it is entirely task dependent. Profiling is the only surefire way to know the best answer. However with that disclaimer if all that a consumer does is a few simple CPU bound calculations then a combining them into a single consumer probably makes the most sense. The moment a task does IO i'd split it out.

**Comment by yuanChina** [comment]
> > I would like to know if this means that putting all the logic into one handler is the best solution Which situation is recommended for us to use 1p2c or 1p3c?
> 
> As @iziamos suggests if you have independent tasks its better to split them into multiple consumers. So that the observed latency of the event is that of the slowest task and not the sequential total.
> 
> There is no generic advice to give about the number of consumers as it is entirely task dependent. Profiling is the only surefire way to know the best answer. However with that disclaimer if all that a consumer does is a few simple CPU bound calculations then a combining them into a single consumer probably makes the most sense. The moment a task does IO i'd split it out.

Thank you, I understand now
